### ISSUE TITLE
Unable to run the project ?

### ISSUE THREAD

**Issue by tariq235** [dreymonde/TheGreatGame#2]
Are there any specific steps to run the project ?

1.  `carthage bootstrap`
2. Run xcodeproject

Error -
1. Ambiguous use of operator '<-'

P.S. I am running Xcode Version 9.0

![screen shot 2017-10-03 at 2 29 55 pm](https://user-images.githubusercontent.com/349211/31112648-7bc92f6c-a847-11e7-8dcc-f17748edd0dd.png)

**Comment by dreymonde** [comment]
Hi! This project is not updated to Swift 4 yet, so there might be some problems with Xcode 9. I’ll look into it when I have time and then get back to you.

**Comment by dreymonde** [comment]
@tariq235 I’ve migrated the project to Swift 4 and everything seems to work now. Have fun exploring the codebase 😄

**Comment by tariq235** [comment]
Great work @dreymonde. Thank you for the quick fix!
